version: '3.0'

services:
  app:
    build: ./
    container_name: meteo_app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - DB_URL=jdbc:postgresql://db:5432/meteo_service
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: 'postgres:16'
    container_name: db
    environment:
      - 'POSTGRES_DB=meteo_service'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'